default-resources:
  - cluster=sbatch
  - slurm_partition='Orion'  
  - runtime="200h"
  - nodes=1
  - jobs=1
  - tasks=1
  - cpus_per_task=1
  - mem_mb_per_cpu=16000
  - tmpdir='/scratch/goreill1/tmp/'
  - mem_mb=None
  - disk_mb=None

set-resources:
  - bwa_sampe:cpus_per_task=8
  - MakeAlleleFreq:cpus_per_task=1
  - MakeAlleleFreq:mem-per-cpu=640G
  - MakeAlleleFreq:mem_mb_per_cpu=640000
  - Genotype_SVs:cpus_per_task=1
  - Genotype_SVs:mem-per-cpu=640G
  - pNpS_per_gene:cpus_per_task=1
  - pNpS_per_gene:mem-per-cpu=640G
  - pNpS_per_gene:mem_mb_per_cpu=640000